name: Python CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Correctness Tests
        run: python -m unittest tests/test_correctness.py

      - name: Run Performance Tests
        run: python -m unittest tests/test_performance.py
